name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # Update package list
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Install Trivy
        run: |
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION#v}_Linux-64bit.deb
          rm trivy_${TRIVY_VERSION#v}_Linux-64bit.deb

      - name: Run Trivy Security Scan
        run: |
          sudo trivy image --exit-code 1 --severity HIGH,CRITICAL my-lightweight-app:latest || true
